#!/usr/bin/env python3
"""Patch the completed Figure 1-6 source manifest for final submission tracing."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path.cwd()
INPUT = ROOT / "figure_1_to_6_panel_source_manifest_COMPLETED.tsv"
OUTPUT = ROOT / "figure_1_to_6_panel_source_manifest_FINAL.tsv"
NOTE = ROOT / "figure_6g_resolution_note.md"

FIG6G_SOURCE = Path(
    "/Volumes/T9/PGCS/figure_reconstruction_v3/source_data/"
    "Figure_7_panel_g_source_data_v5.tsv"
)
FIG6G_CANDIDATES = [
    "/Volumes/T9/PGCS/figure_reconstruction_v3/source_data/Figure_7_panel_g_corrected_source_data.tsv",
    "/Volumes/T9/PGCS/figure_reconstruction_v3/source_data/Figure_7_panel_g_source_data.tsv",
    "/Volumes/T9/PGCS/figure_reconstruction_v3/source_data/Figure_7_panel_g_source_data_v4.tsv",
    str(FIG6G_SOURCE),
]


def clean_action_required(row: dict[str, str]) -> None:
    status = row.get("source_status", "")
    path = row.get("exact_source_file_path", "")
    existence = row.get("path_existence_check", "")

    if status == "SOURCE_CONFIRMED" and path and existence == "all_paths_exist":
        row["action_required"] = "NO_ACTION_REQUIRED_EXCEPT_FINAL_LABEL_CHECK"
    elif status == "SOURCE_NOT_REQUIRED_SCHEMATIC":
        row["action_required"] = "NO_NUMERIC_SOURCE_REQUIRED"
    elif status == "SOURCE_PARTIAL":
        row["action_required"] = "SOURCE_PARTIAL_ACCEPTABLE_WITH_CAPTION_SUPPORT"
    elif status in {"SOURCE_AMBIGUOUS", "SOURCE_AMBIGUOUS_REQUIRES_REBUILD"}:
        row["action_required"] = "RESOLVE_BEFORE_SUBMISSION"


def patch_figure_6g(row: dict[str, str]) -> None:
    row["likely_source_data_or_analysis_output"] = str(FIG6G_SOURCE)
    row["source_status"] = "SOURCE_CONFIRMED"
    row["exact_source_file_path"] = str(FIG6G_SOURCE)
    row["source_file_type"] = "TSV"
    row["analysis_step"] = (
        "Tumor-cell-only boundary score comparison for the tumor-like plasticity "
        "branch; generated by plot_figure_7_tumor_like_plasticity_v5.py and "
        "retained unchanged in the v6 visual polish."
    )
    row["reproducibility_status"] = "REPRODUCIBLE_FROM_SOURCE"
    row["notes"] = (
        "Resolved to Figure_7_panel_g_source_data_v5.tsv based on convergent "
        "evidence: the v5 plotting script writes this file, the v5 log exports "
        "it with 3750 rows, final_micro/final_1percent polish reports cite this "
        "file and retain d=-0.02/q=0.195 and d=-0.11/q=0.125 annotations, and "
        "the v5 inventory records the tumor-cell-only filter and q-value fields. "
        "The corrected_source_data file was an intermediate audit output; the "
        "original all-cell source and v4 table are superseded by v5."
    )
    row["candidate_files"] = "; ".join(FIG6G_CANDIDATES)
    row["path_existence_check"] = (
        "all_paths_exist" if FIG6G_SOURCE.exists() else "selected_path_missing"
    )


def write_note() -> None:
    status = "exists" if FIG6G_SOURCE.exists() else "missing"
    NOTE.write_text(
        "\n".join(
            [
                "# Figure 6G Source Resolution Note",
                "",
                "## Resolution",
                "",
                (
                    "Figure 6G (`Boundary score comparison`) is assigned to the "
                    "following source-data file:"
                ),
                "",
                f"- `{FIG6G_SOURCE}`",
                "",
                f"Path check: `{status}`.",
                "",
                "## Evidence Used",
                "",
                (
                    "- `plot_figure_7_tumor_like_plasticity_v5.py` writes "
                    "`Figure_7_panel_g_source_data_v5.tsv` for panel g and records "
                    "the same file in the v5 source-data inventory."
                ),
                (
                    "- `Figure_7_tumor_like_plasticity_state_v5.log` reports export "
                    "of `Figure_7_panel_g_source_data_v5.tsv` with 3750 rows."
                ),
                (
                    "- `final_micro_polish_report.md` identifies panel g as the only "
                    "Figure 7 panel changed in that pass and lists "
                    "`source_data/Figure_7_panel_g_source_data_v5.tsv`; it reports "
                    "the tumor-cells-only comparison and retained statistics "
                    "`d=-0.02, q=0.195` and `d=-0.11, q=0.125`."
                ),
                (
                    "- `final_1percent_polish_report.md` states that v6 changed only "
                    "panel-g annotation placement/size and that the panel-g source "
                    "data remained unchanged from v5."
                ),
                (
                    "- `audit/Figure_7_panel_g_source_data_inventory_v5.tsv` records "
                    "the tumor-cell-only filter, group labels, source-data path, "
                    "sample counts (`n_top=469`, `n_other=1406`) and BH-FDR q-values."
                ),
                (
                    "- File modification order is consistent with this lineage: the "
                    "original all-cell source predates the corrected audit output; "
                    "v4 follows the audit correction; v5 is the later final "
                    "source-data table used by the polished figure lineage."
                ),
                "",
                "## Superseded Candidates",
                "",
                (
                    "- `Figure_7_panel_g_source_data.tsv`: older all-cell v3 source; "
                    "superseded by tumor-cell-only correction."
                ),
                (
                    "- `Figure_7_panel_g_corrected_source_data.tsv`: intermediate "
                    "audit-correction output, not the final figure-lineage source."
                ),
                (
                    "- `Figure_7_panel_g_source_data_v4.tsv`: tumor-cell-only "
                    "version preceding v5; superseded by v5 in final polish."
                ),
                "",
                "## Submission Impact",
                "",
                (
                    "Figure 6G does not block submission after this patch, provided "
                    "the final label/caption check keeps the result framed as "
                    "tumor-like plasticity being distinct from regenerative "
                    "competence, not as evidence of regeneration equivalence."
                ),
                "",
                "Rebuild required: `no`.",
                "",
                (
                    "Move to supplementary if unresolved: `not required`; if a future "
                    "visual audit finds that the displayed panel no longer matches the "
                    "v5 source statistics, the preferred fix would be to rebuild the "
                    "panel from the v5 source rather than move it."
                ),
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    with INPUT.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        rows = list(reader)
        fieldnames = reader.fieldnames

    if not fieldnames:
        raise SystemExit(f"No header found in {INPUT}")

    patched_6g = False
    for row in rows:
        if row.get("figure_id") == "Figure 6" and row.get("panel_id") == "G":
            patch_figure_6g(row)
            patched_6g = True
        clean_action_required(row)

    if not patched_6g:
        raise SystemExit("Figure 6 panel G row was not found.")

    with OUTPUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, delimiter="\t", fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    write_note()


if __name__ == "__main__":
    main()
